### ISSUE TITLE
Evaluate possibility to have dynamic Icons

### ISSUE THREAD

**Issue by luciob** [melfore/mosaic#166]
MUI provides a way to have icons through font library (see: https://material-ui.com/components/icons/#icon-font-icons and  https://google.github.io/material-design-icons/#icon-font-for-the-web).

It's not clear however if this can be somehow wrapped in Mosaic as the import for the fonts is to be done via html:
`<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />`

An alternative way could be to create a `MosaicContext` that loads asynchronously the icon set and then makes it available.
This requires for sure understanding of feasibility in order to proceed.

CC: @erosval

**Comment by erosval** [comment]
It might be useful to have the ability to use directly the icons provided by Material UI or something similar to SvgIcon
