### ISSUE TITLE
Add icon FileCopy to available icons

### ISSUE THREAD

**Issue by paologaletti72** [melfore/mosaic#204]

**Comment by luciob** [comment]
Hi @paologaletti72, issue has already been solved together with #166 

You can have a look below (example with Button component):
1. Import icon from material-ui icon:
```
import PowerBIIcon from "@material-ui/icons/Assessment";
import {​​​​​​​​ Button, Icons }​​​​​​​​ from "@melfore/mosaic";
```
2. Usage with material-ui icon:
```
<Button icon={​​​​​​​​{​​​​​​​​ component: <PowerBIIcon /> }​​​​​​​​}​​​​​​​​ label="PowerBi" onClick={​​​​​​​​() => {​​​​​​​​}​​​​​​​​}​​​​​​​​ />
```
3. Usage with standard Mosaic icon:
```
<Button icon={​​​​​​​​{​​​​​​​​ name: Icons.refresh }​​​​​​​​}​​​​​​​​ label="Refresh" onClick={​​​​​​​​() => {​​​​​​​​}​​​​​​​​}​​​​​​​​ />
```

Find examples in each component's storybook (e.g. for Button: https://melfore.github.io/mosaic/?path=/docs/button--canvas#custom-icon)
