### ISSUE TITLE
[Appbar] Ability to add tooltip on actions

### ISSUE THREAD

**Issue by gabrielepolizzotto-bitrocketdev** [melfore/mosaic#258]
Icons inside the actions parameters can be vague, so i believe it's a good idea to add the tooltip, in order to show the user which action he is going to perform.
After reading the code, i think we can easily achieve this feature extending IAppBarActions in order to accept tooltipValue string.
When we create the actual component, if the tooltipValue exist will be wrapped inside MUI tooltip component.

What do you think?
I can make a PR.

**Comment by luciob** [comment]
Hi @gabrielepolizzotto-bitrocketdev thank you for reporting this ticket.
We already have two related items #167 and #169.
If you don't mind I take the suggestion and implement this as I have some related work to do.
I'll set you as reviewer of the PR and requiring your approval for merging. 
👍
