### ISSUE TITLE
Implement Select component

### ISSUE THREAD

**Issue by luciobordonaro** [melfore/mosaic#27]
Implement `Select` component based on what done for `SelectRingTypeAC` and `SelectRingTypeACMul` in reference project.

Component should be generic enough to allow plugging external data-sources for `Autocomplete` feature.

Take in consideration #101 to handle type `<Select<OptionData>>`.

**Comment by erosval** [comment]
To be more complete I also suggest to look at `SelectIPDefACMul` component as this contains also grouping management.
