### ISSUE TITLE
[Table] sticky header issue

### ISSUE THREAD

**Issue by alessandrotilli** [melfore/mosaic#278]
With the last changes introduced by #274 there are some issues when table has sticky header and tableLayout "auto" as seen in the screen recording:

https://user-images.githubusercontent.com/2563389/203015636-d341384e-9774-4dcc-8c30-68e18fbe6496.mov

**Comment by luciob** [comment]
Hi @alessandrotilli, I'm going to work today on some minor changes. If you agree I'd like to solve it pragmatically: if `tableLayout` is set to `auto` then you have `sticky` set to `false` by default.
Allowing scroll in both directions is not so compatible with sticky headers.
What do you think? Can I proceed in this way?

**Comment by alessandrotilli** [comment]
Hi @luciob, i've just onpened a this [PR](https://github.com/melfore/mosaic/pull/279) with a possible way to fix this.
I know it uses some "magic number" trickery to adjust some sizes but it seems to work fine in different browsers.

If you think it's safer to enable scroll in one direction only it's ok for me!
