### ISSUE TITLE
[Table] issues with primary action

### ISSUE THREAD

**Issue by alessandrotilli** [melfore/mosaic#289]
Hello, when table has a `primary` action there are some unwanted behaviour as shown in the attached video

https://user-images.githubusercontent.com/2563389/209170464-3bf85868-3415-4a71-950b-69227ffe192f.mov

- when selection checkbox are visibile, the primary column moves before them, I think it will be better keeping the checkboxes in the first column
- if table has a sticky header there some zindex issues

**Comment by luciob** [comment]
Hi @alessandrotilli will work on it today 👍

**Comment by alessandrotilli** [comment]
Great, thank you! 🙏
