### ISSUE TITLE
Allow install on react 18 projects

### ISSUE THREAD

**Issue by alessandrotilli** [melfore/mosaic#296]
Hi, trying to install on react 18 projects will lead to an unresolved dependency error

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: [REDACTED]
npm ERR! Found: @types/react@18.0.37
npm ERR! node_modules/@types/react
npm ERR!   @types/react@"^18.0.35" from the root project
npm ERR!   peerOptional @types/react@"^17.0.0 || ^18.0.0" from @mui/icons-material@5.11.16
npm ERR!   node_modules/@mui/icons-material
npm ERR!     @mui/icons-material@"^5.11.16" from the root project
npm ERR!     peer @mui/icons-material@">= 5.5.1 < 6" from @melfore/mosaic@7.7.0-beta.1
npm ERR!     node_modules/@melfore/mosaic
npm ERR!       @melfore/mosaic@"7.7.0-beta.1" from the root project
npm ERR!   1 more (@mui/material)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @types/react@"^17.0.0" from @mui/styles@5.12.0
npm ERR! node_modules/@mui/styles
npm ERR!   peer @mui/styles@">= 5.5.3 < 6" from @melfore/mosaic@7.7.0-beta.1
npm ERR!   node_modules/@melfore/mosaic
npm ERR!     @melfore/mosaic@"7.7.0-beta.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

A basic first step could be changing the react version in the `peerDependencies`, something like this for example.

```diff
   "peerDependencies": {
     "@emotion/react": ">= 11.8.2 < 12",
     "@emotion/styled": ">= 11.8.1 < 12",
     "@mui/icons-material": ">= 5.5.1 < 6",
     "@mui/material": ">= 5.5.3 < 6",
     "@mui/styles": ">= 5.5.3 < 6",
-    "react": ">= 17 < 18",
-    "react-dom": ">= 17 < 18"
+    "react": ">= 17 < 19",
+    "react-dom": ">= 17 < 19"
   },
```
just to allow installs and start testing in a real world application

Next steps for a full react 18 compatibility will require dropping `@mui/mui/styles` and maybe switch to react-testing-library for testing since react 18 is not supported (there's an unofficial adapter [here](https://github.com/cfaester/enzyme-adapter-react-18) but results are unknown)

**Comment by luciob** [comment]
Hi @alessandrotilli, thanks for opening the ticket. 
I'd proceed creating a dedicated issue for the testing part.
Moreover I also think pipelines need to be changed for updating node version (currently 12.x).
I'll take care of the changes and let you know since I'll need your support for testing on a real react 18 project.

**Comment by luciob** [comment]
Hi @alessandrotilli and @erosval I've just released a new beta version with React 18 support.
Please check the changelog and perform an install test.
https://github.com/melfore/mosaic/releases/tag/v7.7.0-beta.2

Let me know in case of issues 👍
