### ISSUE TITLE
[Storybook] Verify output without TS docgen

### ISSUE THREAD

**Issue by luciob** [melfore/mosaic#379]
Following [announce](https://storybook.js.org/blog/optimize-storybook-7-6/) by Storybook team, there are some performances improvement related to build and test process.

### Removal of TS docgen
Currently Storybook uses an internal plugin called react-docgen-typescript to generate the props table of React TS components. Following announcement by Storybook team, looks like the react-docgen-typescript is very slow and adds complexity to the process due to the dependency on TS. They suggest using and configuring react-docgen plugin to generate docs.

Check the **2.2x faster React docgen** chapter of linked announce.

Let's test if this is beneficial also for us, considering that we need to avoid regressions on generated documentation.

**Comment by CrisGrud** [comment]
Storybook build process using --test flag is faster: 10sec instead of 1.03min.

--Test exlude also coverage doc from build, to avoid this exlusion you have to modify file .storybook/main.ts:
```
build: {
    test: {
      disableSourcemaps: false,
      disabledAddons: ["@storybook/addon-docs", "@storybook/addon-essentials/docs"],
    },
  },
```

Test with new build method presents some error like:
SnapShot match:
```
 -      style="cursor: pointer;"
 +      style="cursor: default;"
```
and function error:
Message:
    ` M is not a function`

**Comment by luciob** [comment]
This is not working for us. The library is strongly typed, removing the `react-docgen-typescript` plugin causes a poor quality in output documentation. For instance have a look at the `Avatar` component:

- with typescript docgen
<img width="1036" alt="Screenshot 2024-01-30 at 15 19 44" src="https://github.com/melfore/mosaic/assets/61870694/a7a28dcf-154b-43af-9eca-b056a7aeb9fb">

- without typescript docgen

<img width="1032" alt="Screenshot 2024-01-30 at 15 20 18" src="https://github.com/melfore/mosaic/assets/61870694/71adabd2-8372-4a8d-ab91-2e3371012b89">
