### ISSUE TITLE
Specify browser in env files

### ISSUE THREAD

**Issue by luciob** [melfore/mosaic#42]
Apparently it seems that `.env` files are ignored when launching `storybook`.
Investigate if there are some known issues.

**Comment by luciobordonaro** [comment]
We are not lucky here @masmau .
This is a StoryBook bug, it simply ignores local env settings.
There have been several requests to implement this without luck, see for instance [this](https://github.com/storybookjs/storybook/issues/6618) and also [this](https://github.com/storybookjs/storybook/issues/7975).

The only option is to try with this flag when starting storybook `--ci                          CI mode (skip interactive prompts, don't open browser)` and run it in the preferred browser using for instance a bookmark.

**Comment by luciob** [comment]
Storybook chooses the browser to use with `better-opn` package.
Set the `BROWSER` env variable with the name of the browser of your choice.
Set `BROWSER=none` to avoid opening in any browser.
