### ISSUE TITLE
Package installation deletes necessary modules

### ISSUE THREAD

**Issue by masmau** [melfore/mosaic#61]
`mosaic` library npm installation removes `react`, `react-dom`, ... from `node_modules` directory.

Steps to reproduce the issue: 
1. npx create-react-app my-app --template typescript
2. npm start *# test*
The application works.

3. npm i @melfore/mosaic ***# removes react etc***
4. npm start *# test*
An error is raised: `Module not found: Can't resolve 'react' in '/home/mas/dev/tmp/prova_import/my-app/src'`

**Comment by erosval** [comment]
Just installing the package breaks the building of applications.

Look for example: https://gitlab.com/digitalnology/kyp/kyp-web/-/jobs/507577061

**Comment by luciobordonaro** [comment]
I'm not able to reproduce this issue with the steps you reported the new cra-based project runs fine. Let's make a quick screen share to understand this better.

However I would have moved `react` and `react-related` to dev-deps before, but I guess it's time to do it now! 😅
