### ISSUE TITLE
Improve documentation of enumerated types

### ISSUE THREAD

**Issue by luciob** [melfore/mosaic#92]
We have some components like `Icons` and `Typography` that are focused on the correct usage of enumerations.

Right now to display all available enumerations combo I made a programmatic loop that prints all combos. This is fine for displaying the doc but it blocks users from doing copy and paste of code.

Let's find a way to display correctly all combos allowing users to do copy and paste of ready to use components.

**Comment by luciobordonaro** [comment]
In addition: for components that require some `enums` it would be beneficial to list those in the section of custom documentation (near import / usage / intl).

**Comment by luciob** [comment]
Deprecated
